export interface MessageBodyProps {
  isChessCountdownActive?: boolean;
  isOmokCountdownActive?: boolean;
  partner: any;
  channelId: number;
  currentChannel: any;
  displayedThemeColor: string;
  groupObjs: any;
  isAIMessage: boolean;
  isCielMessage?: boolean;
  isAICardModalShown: boolean;
  isApprovalRequest: boolean;
  isModificationNotice: boolean;
  message: any;
  nextMessageHasTopic: boolean;
  prevMessageHasTopic: boolean;
  onDelete: (v: any) => void;
  index: number;
  isBanned: boolean;
  isLastMsg: boolean;
  isNotification: boolean;
  isRestricted: boolean;
  isEditing: boolean;
  loading: boolean;
  onAcceptGroupInvitation: (v: any) => void;
  onChessBoardClick: () => void;
  onChessSpoilerClick: (v: number) => void;
  onOmokBoardClick: () => void;
  onOmokSpoilerClick: (v: number) => void;
  onCancelRewindRequest: () => void;
  onAcceptRewind: (v: any) => void;
  onDeclineRewind: () => void;
  onReceiveNewMessage: () => void;
  onAiUsagePolicyUpdate?: (policy?: any) => void;
  onOptimisticAiMessageSaveError?: (payload: {
    content?: string;
    error?: any;
    aiUsagePolicy?: any;
    channelId?: number;
    subchannelId?: number;
    topicId?: number;
  }) => void;
  onReplyClick: (target: any) => void;
  onRequestRewind: (v: any) => void;
  onSetAICardModalCardId: (v: any) => void;
  onSetChessTarget: (v: any) => void;
  onSetGroupObjs: (v: any) => void;
  onSetMessageToScrollTo: (v: any) => void;
  onSetTransactionModalShown: (v: boolean) => void;
  onRewardMessageSubmit: (v: any) => void;
  onShowSubjectMsgsModal: (v: any) => void;
  recentThumbUrl: string;
  zIndex?: number;
}
