import React, { useMemo } from 'react';
import UserDetails from '~/components/UserDetails';
import ProfilePic from '~/components/ProfilePic';
import { useNavigate } from 'react-router-dom';
import { useChatContext } from '~/contexts';
import { borderRadius, Color, mobileMaxWidth } from '~/constants/css';
import { css } from '@emotion/css';

export default function DefaultComponent({
  isPreview,
  src,
  pageType,
  subPageType,
  profile
}: {
  isPreview?: boolean;
  src: string;
  pageType?: string;
  subPageType?: string;
  profile: {
    id: number;
    username: string;
    profilePicUrl: string;
  };
  profileId: number;
}) {
  const navigate = useNavigate();
  const chatStatus = useChatContext((v) => v.state.chatStatus);
  const heading = useMemo(() => {
    switch (pageType) {
      case 'watched':
        return `XP Videos Watched by ${profile.username}`;
      case 'likes':
        return `All Contents Liked by ${profile.username}`;
      case 'all':
        if (subPageType === 'byuser') {
          return `All Contents Made by ${profile.username}`;
        }
        return `All Contents Posted by ${profile.username}`;
      case 'comments':
        return `All Comments Posted by ${profile.username}`;
      case 'subjects':
        if (subPageType === 'byuser') {
          return `Subjects Made by ${profile.username}`;
        }
        return `Subjects Posted by ${profile.username}`;
      case 'ai-stories':
        return `AI Stories Generated by ${profile.username}`;
      case 'videos':
        if (subPageType === 'byuser') {
          return `Videos Made by ${profile.username}`;
        }
        return `Videos posted by ${profile.username}`;
      case 'links':
        if (subPageType === 'byuser') {
          return `Links made by ${profile.username}`;
        }
        return `Links posted by ${profile.username}`;
      default:
        return '';
    }
  }, [pageType, profile?.username, subPageType]);

  if (isPreview) {
    return (
      <button
        type="button"
        className={compactUserPreviewClass}
        onClick={handlePreviewClick}
      >
        {heading ? (
          <div className="compact-user-embed__heading">{heading}</div>
        ) : null}
        <div className="compact-user-embed__body">
          <ProfilePic
            style={{ width: '5.7rem', flexShrink: 0 }}
            userId={profile.id}
            profilePicUrl={profile.profilePicUrl || ''}
            online={chatStatus[profile.id]?.isOnline}
            statusShown
          />
          <div className="compact-user-embed__copy">
            <span>Profile</span>
            <strong>{profile.username || 'User'}</strong>
            {getProfilePreviewText(profile) ? (
              <p>{getProfilePreviewText(profile)}</p>
            ) : null}
          </div>
        </div>
      </button>
    );
  }

  return (
    <div
      onClick={() => navigate(src)}
      className={css`
        .label {
          font-size: 2.2rem;
          color: ${Color.black()};
        }
        width: 100%;
        background: #fff;
        padding: 1rem;
        transition: background 0.5s;
        border: 1px solid var(--ui-border);
        border-radius: ${borderRadius};
        cursor: pointer;
        &:hover {
          border: 1px solid var(--ui-border-strong);
        }
        @media (max-width: ${mobileMaxWidth}) {
          .label {
            font-size: 1.8rem;
          }
        }
      `}
    >
      {heading ? (
        <div
          className={`label ${css`
            font-weight: bold;
            margin-bottom: 1.5rem;
            overflow-wrap: break-word;
            word-break: break-word;
          `}`}
        >
          {heading}
        </div>
      ) : null}
      <div
        className={css`
          display: flex;
          align-items: center;
          justify-content: space-between;
          width: 100%;
        `}
      >
        <div
          className={css`
            width: 30%;
          `}
        >
          <ProfilePic
            style={{ width: '100%' }}
            userId={profile.id}
            profilePicUrl={profile.profilePicUrl || ''}
            online={chatStatus[profile.id]?.isOnline}
            statusShown
            large
          />
        </div>
        <div
          className={css`
            margin-left: 3rem;
            width: CALC(75% - 3rem);
          `}
        >
          <UserDetails
            noLink
            small
            unEditable
            profile={profile}
            userId={profile.id}
          />
        </div>
      </div>
    </div>
  );

  function handlePreviewClick(event: React.MouseEvent<HTMLButtonElement>) {
    event.stopPropagation();
    navigate(src);
  }
}

function getProfilePreviewText(profile: any) {
  return (
    profile.statusMsg ||
    profile.profileFirstRow ||
    profile.profileSecondRow ||
    profile.profileThirdRow ||
    profile.realName ||
    ''
  );
}

const compactUserPreviewClass = css`
  appearance: none;
  display: flex;
  flex-direction: column;
  justify-content: center;
  gap: 0.5rem;
  width: 100%;
  min-height: 8.6rem;
  padding: 0.78rem 0.9rem;
  overflow: hidden;
  border: 1px solid ${Color.borderGray()};
  border-radius: ${borderRadius};
  background: #fff;
  color: ${Color.darkerGray()};
  font: inherit;
  text-align: left;
  cursor: pointer;
  .compact-user-embed__heading {
    max-width: 100%;
    overflow: hidden;
    color: ${Color.logoBlue()};
    font-size: 1rem;
    font-weight: 900;
    line-height: 1.12;
    text-overflow: ellipsis;
    white-space: nowrap;
  }
  .compact-user-embed__body {
    display: grid;
    grid-template-columns: auto minmax(0, 1fr);
    align-items: center;
    gap: 0.85rem;
    min-width: 0;
  }
  .compact-user-embed__copy {
    display: flex;
    min-width: 0;
    flex-direction: column;
    gap: 0.28rem;
  }
  span {
    overflow: hidden;
    color: ${Color.darkGray()};
    font-size: 1rem;
    font-weight: 900;
    line-height: 1.1;
    text-overflow: ellipsis;
    white-space: nowrap;
  }
  strong {
    overflow: hidden;
    color: ${Color.black()};
    font-size: 1.45rem;
    font-weight: 900;
    line-height: 1.12;
    text-overflow: ellipsis;
    white-space: nowrap;
  }
  p {
    margin: 0;
    overflow: hidden;
    color: ${Color.darkGray()};
    font-size: 1.1rem;
    font-weight: 700;
    line-height: 1.25;
    display: -webkit-box;
    -webkit-box-orient: vertical;
    -webkit-line-clamp: 2;
  }
`;
