import React, { useMemo } from 'react';
import UserDetails from '~/components/UserDetails';
import ProfilePic from '~/components/ProfilePic';
import ProfileEmbedCard from '~/components/ProfileEmbedCard';
import { useNavigate } from 'react-router-dom';
import { useChatContext } from '~/contexts';
import { borderRadius, Color, mobileMaxWidth } from '~/constants/css';
import { css } from '@emotion/css';

export default function DefaultComponent({
  isPreview,
  isChat = false,
  src,
  pageType,
  subPageType,
  profile
}: {
  isPreview?: boolean;
  isChat?: boolean;
  src: string;
  pageType?: string;
  subPageType?: string;
  profile: any;
  profileId: number;
}) {
  const navigate = useNavigate();
  const chatStatus = useChatContext((v) => v.state.chatStatus);
  const heading = useMemo(() => {
    switch (pageType) {
      case 'watched':
        return `XP Videos Watched by ${profile.username}`;
      case 'likes':
        return `All Contents Liked by ${profile.username}`;
      case 'all':
        if (subPageType === 'byuser') {
          return `All Contents Made by ${profile.username}`;
        }
        return `All Contents Posted by ${profile.username}`;
      case 'comments':
        return `All Comments Posted by ${profile.username}`;
      case 'subjects':
        if (subPageType === 'byuser') {
          return `Subjects Made by ${profile.username}`;
        }
        return `Subjects Posted by ${profile.username}`;
      case 'ai-stories':
        return `AI Stories Generated by ${profile.username}`;
      case 'videos':
        if (subPageType === 'byuser') {
          return `Videos Made by ${profile.username}`;
        }
        return `Videos posted by ${profile.username}`;
      case 'links':
        if (subPageType === 'byuser') {
          return `Links made by ${profile.username}`;
        }
        return `Links posted by ${profile.username}`;
      default:
        return '';
    }
  }, [pageType, profile?.username, subPageType]);

  if (isPreview) {
    return (
      <ProfileEmbedCard
        isChat={isChat}
        profile={profile}
        heading={heading}
        online={chatStatus[profile.id]?.isOnline}
        onActivate={handleActivatePreview}
      />
    );
  }

  return (
    <div
      role={isChat ? 'link' : undefined}
      tabIndex={isChat ? 0 : undefined}
      onClick={(event) => {
        if (isChat) {
          if ((event.target as HTMLElement).closest('a,button,input,textarea,select')) return;
          event.stopPropagation();
        }
        navigate(src);
      }}
      onKeyDown={isChat ? (event) => {
        if (event.key !== 'Enter' || event.target !== event.currentTarget) return;
        event.preventDefault();
        event.stopPropagation();
        navigate(src);
      } : undefined}
      className={`${isChat ? chatProfileClass : ''} ${css`
        .label {
          font-size: 2.2rem;
          color: ${Color.black()};
        }
        width: 100%;
        background: #fff;
        padding: 1rem;
        transition: background 0.5s;
        border: 1px solid var(--ui-border);
        border-radius: ${borderRadius};
        cursor: pointer;
        &:hover {
          border: 1px solid var(--ui-border-strong);
        }
        @media (max-width: ${mobileMaxWidth}) {
          .label {
            font-size: 1.8rem;
          }
        }
      `}`}
    >
      {heading ? (
        <div
          className={`label ${css`
            font-weight: bold;
            margin-bottom: 1.5rem;
            overflow-wrap: break-word;
            word-break: break-word;
          `}`}
        >
          {heading}
        </div>
      ) : null}
      <div
        className={`profile-attachment__body ${css`
          display: flex;
          align-items: center;
          justify-content: space-between;
          width: 100%;
        `}`}
      >
        <div
          className={`profile-attachment__avatar ${css`
            width: 30%;
          `}`}
        >
          <ProfilePic
            style={{ width: '100%' }}
            userId={profile.id}
            profilePicUrl={profile.profilePicUrl || ''}
            online={chatStatus[profile.id]?.isOnline}
            statusShown
            statusSize={isChat ? 'dot' : undefined}
            large
          />
        </div>
        <div
          className={`profile-attachment__details ${css`
            margin-left: 3rem;
            width: CALC(75% - 3rem);
          `}`}
        >
          <UserDetails
            isChatEmbed={isChat}
            noLink
            small
            unEditable
            profile={profile}
            userId={profile.id}
          />
        </div>
      </div>
    </div>
  );

  function handleActivatePreview() {
    navigate(src);
  }
}

const chatProfileClass = css`
  && {
    container: chatProfileAttachment / inline-size;
    min-width: 0;
    padding: 14px;
    border-color: #dce3ed;
    border-radius: 14px;
    .label { color: #334155; font-size: 15px; line-height: 1.5; }
    .profile-attachment__body {
      display: flex;
      flex-direction: column;
      align-items: center;
      gap: 12px;
    }
    .profile-attachment__avatar { width: 64px; flex-shrink: 0; }
    .profile-attachment__details { min-width: 0; width: 100%; margin-left: 0; }
    &:focus-visible { outline: 2px solid #334155; outline-offset: 3px; }
    @container chatProfileAttachment (min-width: 360px) {
      .profile-attachment__body { flex-direction: row; align-items: flex-start; }
      .profile-attachment__details { flex: 1; }
    }
  }
`;
