// GENERATED by quest/media/build.mjs — do not edit. Grammar Quest's art and
// music are served from the CDN under grammar-quest/v1/ with content-hashed names
// (cached forever); this maps each logical path to its file.
export const GQ_MEDIA_PREFIX = 'grammar-quest/v1';
export const GQ_MEDIA: Record<string, string> = {
  'img/grammar-quest/arenas/w1-castle.png':
    'img/arenas/w1-castle.8dfd38aed1.webp',
  'img/grammar-quest/arenas/w1-fort.png': 'img/arenas/w1-fort.400a83ecb8.webp',
  'img/grammar-quest/arenas/w10-castle.png':
    'img/arenas/w10-castle.dc539c7a88.webp',
  'img/grammar-quest/arenas/w10-fort.png':
    'img/arenas/w10-fort.da8813a3e2.webp',
  'img/grammar-quest/arenas/w2-castle.png':
    'img/arenas/w2-castle.2328e5a2c9.webp',
  'img/grammar-quest/arenas/w2-fort.png': 'img/arenas/w2-fort.727f524f74.webp',
  'img/grammar-quest/arenas/w3-castle.png':
    'img/arenas/w3-castle.9726a2e8f4.webp',
  'img/grammar-quest/arenas/w3-fort.png': 'img/arenas/w3-fort.3d73b6cc0d.webp',
  'img/grammar-quest/arenas/w4-castle.png':
    'img/arenas/w4-castle.c5939e74ad.webp',
  'img/grammar-quest/arenas/w4-fort.png': 'img/arenas/w4-fort.e2a4c5c492.webp',
  'img/grammar-quest/arenas/w5-castle.png':
    'img/arenas/w5-castle.a515d837a5.webp',
  'img/grammar-quest/arenas/w5-fort.png': 'img/arenas/w5-fort.07ff91bf3f.webp',
  'img/grammar-quest/arenas/w6-castle.png':
    'img/arenas/w6-castle.3912f961fc.webp',
  'img/grammar-quest/arenas/w6-fort.png': 'img/arenas/w6-fort.8afe824636.webp',
  'img/grammar-quest/arenas/w7-castle.png':
    'img/arenas/w7-castle.6ca16daa8d.webp',
  'img/grammar-quest/arenas/w7-fort.png': 'img/arenas/w7-fort.b6090bf957.webp',
  'img/grammar-quest/arenas/w8-castle.png':
    'img/arenas/w8-castle.ec05dc7453.webp',
  'img/grammar-quest/arenas/w8-fort.png': 'img/arenas/w8-fort.605f39f11d.webp',
  'img/grammar-quest/arenas/w9-castle.png':
    'img/arenas/w9-castle.ea771e6c15.webp',
  'img/grammar-quest/arenas/w9-fort.png': 'img/arenas/w9-fort.3a555731ee.webp',
  'img/grammar-quest/classic-bg.jpg': 'img/classic-bg.9416bfe581.webp',
  'img/grammar-quest/classic-logo.png': 'img/classic-logo.fc27a77ead.webp',
  'img/grammar-quest/cover-classic.jpg': 'img/cover-classic.697d9920a1.webp',
  'img/grammar-quest/cover-quest.jpg': 'img/cover-quest.582dfe9135.webp',
  'img/grammar-quest/forest-of-clauses.jpg':
    'img/forest-of-clauses.483459136c.webp',
  'img/grammar-quest/harbor-town.jpg': 'img/harbor-town.e5cec428e4.webp',
  'img/grammar-quest/levels/w1-firefly-night.png':
    'img/levels/w1-firefly-night.a1762d1c8c.webp',
  'img/grammar-quest/levels/w1-flower-meadow.png':
    'img/levels/w1-flower-meadow.003626e941.webp',
  'img/grammar-quest/levels/w1-kite-hills.png':
    'img/levels/w1-kite-hills.7ee6030de0.webp',
  'img/grammar-quest/levels/w1-lantern-festival.png':
    'img/levels/w1-lantern-festival.7687f9b3bf.webp',
  'img/grammar-quest/levels/w1-mushroom-grove.png':
    'img/levels/w1-mushroom-grove.bc0d71771a.webp',
  'img/grammar-quest/levels/w1-orchard.png':
    'img/levels/w1-orchard.1289c4ee6f.webp',
  'img/grammar-quest/levels/w1-pond-shallows.png':
    'img/levels/w1-pond-shallows.bd101e52b7.webp',
  'img/grammar-quest/levels/w1-rainy-lanes.png':
    'img/levels/w1-rainy-lanes.e032f5be9a.webp',
  'img/grammar-quest/levels/w1-village-morning.png':
    'img/levels/w1-village-morning.c67bf73e15.webp',
  'img/grammar-quest/levels/w1-village-sunset.png':
    'img/levels/w1-village-sunset.eb0eafe1b0.webp',
  'img/grammar-quest/levels/w10-asteroid-belt.png':
    'img/levels/w10-asteroid-belt.d5f0ce11b4.webp',
  'img/grammar-quest/levels/w10-black-hole.png':
    'img/levels/w10-black-hole.fdcec99906.webp',
  'img/grammar-quest/levels/w10-candy-land.png':
    'img/levels/w10-candy-land.216b5910be.webp',
  'img/grammar-quest/levels/w10-chess-land.png':
    'img/levels/w10-chess-land.016b14446f.webp',
  'img/grammar-quest/levels/w10-clockwork.png':
    'img/levels/w10-clockwork.47640353cd.webp',
  'img/grammar-quest/levels/w10-cosmic-garden.png':
    'img/levels/w10-cosmic-garden.c64341109c.webp',
  'img/grammar-quest/levels/w10-crystal-palace.png':
    'img/levels/w10-crystal-palace.1fd969e9b6.webp',
  'img/grammar-quest/levels/w10-glitch-world.png':
    'img/levels/w10-glitch-world.b167ac4135.webp',
  'img/grammar-quest/levels/w10-mirror-world.png':
    'img/levels/w10-mirror-world.fb9f47760c.webp',
  'img/grammar-quest/levels/w10-moon-surface.png':
    'img/levels/w10-moon-surface.98f74bdc99.webp',
  'img/grammar-quest/levels/w10-nebula.png':
    'img/levels/w10-nebula.f5af30415e.webp',
  'img/grammar-quest/levels/w10-neon-circuit.png':
    'img/levels/w10-neon-circuit.0212e2b87f.webp',
  'img/grammar-quest/levels/w10-pipe-maze.png':
    'img/levels/w10-pipe-maze.e3279b8f54.webp',
  'img/grammar-quest/levels/w10-space-station.png':
    'img/levels/w10-space-station.58976ed398.webp',
  'img/grammar-quest/levels/w10-tower-summit.png':
    'img/levels/w10-tower-summit.bf04e979e8.webp',
  'img/grammar-quest/levels/w10-zero-g-library.png':
    'img/levels/w10-zero-g-library.bb57276ea0.webp',
  'img/grammar-quest/levels/w2-coral-reef.png':
    'img/levels/w2-coral-reef.9f16c90097.webp',
  'img/grammar-quest/levels/w2-harbor-docks.png':
    'img/levels/w2-harbor-docks.2c5e652226.webp',
  'img/grammar-quest/levels/w2-harbor-sunset.png':
    'img/levels/w2-harbor-sunset.b33c340e86.webp',
  'img/grammar-quest/levels/w2-lighthouse-night.png':
    'img/levels/w2-lighthouse-night.c4c5cbfaed.webp',
  'img/grammar-quest/levels/w2-pirate-airship.png':
    'img/levels/w2-pirate-airship.51b087e969.webp',
  'img/grammar-quest/levels/w2-sandy-beach.png':
    'img/levels/w2-sandy-beach.ab6b130e63.webp',
  'img/grammar-quest/levels/w2-sea-caves.png':
    'img/levels/w2-sea-caves.41acbc4308.webp',
  'img/grammar-quest/levels/w2-shipwreck.png':
    'img/levels/w2-shipwreck.a0f6cf3cc8.webp',
  'img/grammar-quest/levels/w2-tide-pools.png':
    'img/levels/w2-tide-pools.2e08cd48cc.webp',
  'img/grammar-quest/levels/w3-barn-yard.png':
    'img/levels/w3-barn-yard.7a2d7e2c64.webp',
  'img/grammar-quest/levels/w3-cloud-hop.png':
    'img/levels/w3-cloud-hop.d326411dd1.webp',
  'img/grammar-quest/levels/w3-hot-air-balloons.png':
    'img/levels/w3-hot-air-balloons.10253ddc86.webp',
  'img/grammar-quest/levels/w3-rainbow-meadow.png':
    'img/levels/w3-rainbow-meadow.0205cfb750.webp',
  'img/grammar-quest/levels/w3-starry-hills.png':
    'img/levels/w3-starry-hills.716ca3273d.webp',
  'img/grammar-quest/levels/w3-tulip-fields.png':
    'img/levels/w3-tulip-fields.43fdb1c151.webp',
  'img/grammar-quest/levels/w3-wheat-sunset.png':
    'img/levels/w3-wheat-sunset.fd1b94c632.webp',
  'img/grammar-quest/levels/w3-windmill-fields.png':
    'img/levels/w3-windmill-fields.42d840755f.webp',
  'img/grammar-quest/levels/w4-autumn-woods.png':
    'img/levels/w4-autumn-woods.5eb323b7f3.webp',
  'img/grammar-quest/levels/w4-fairy-glen.png':
    'img/levels/w4-fairy-glen.335fd6dc6b.webp',
  'img/grammar-quest/levels/w4-firefly-river.png':
    'img/levels/w4-firefly-river.eec3d2cdd6.webp',
  'img/grammar-quest/levels/w4-forest-path.png':
    'img/levels/w4-forest-path.9028880e1b.webp',
  'img/grammar-quest/levels/w4-glow-mushroom-night.png':
    'img/levels/w4-glow-mushroom-night.09d08ef231.webp',
  'img/grammar-quest/levels/w4-hollow-log.png':
    'img/levels/w4-hollow-log.c7bf9fcf34.webp',
  'img/grammar-quest/levels/w4-river-rapids.png':
    'img/levels/w4-river-rapids.a8b1f4ae2b.webp',
  'img/grammar-quest/levels/w4-spider-woods.png':
    'img/levels/w4-spider-woods.0d40812b7c.webp',
  'img/grammar-quest/levels/w4-swamp.png':
    'img/levels/w4-swamp.e3fef5a94a.webp',
  'img/grammar-quest/levels/w4-treetops.png':
    'img/levels/w4-treetops.89e69120ee.webp',
  'img/grammar-quest/levels/w4-waterfall-cliffs.png':
    'img/levels/w4-waterfall-cliffs.90e6509df1.webp',
  'img/grammar-quest/levels/w5-canyon-day.png':
    'img/levels/w5-canyon-day.37fb43ccac.webp',
  'img/grammar-quest/levels/w5-crystal-caves.png':
    'img/levels/w5-crystal-caves.f29a283b2a.webp',
  'img/grammar-quest/levels/w5-desert-dunes.png':
    'img/levels/w5-desert-dunes.80066b5194.webp',
  'img/grammar-quest/levels/w5-desert-night.png':
    'img/levels/w5-desert-night.f0f56c7e2e.webp',
  'img/grammar-quest/levels/w5-lava-vents.png':
    'img/levels/w5-lava-vents.7808366dd1.webp',
  'img/grammar-quest/levels/w5-mine-cart.png':
    'img/levels/w5-mine-cart.e57f684877.webp',
  'img/grammar-quest/levels/w5-oasis.png':
    'img/levels/w5-oasis.ec50263433.webp',
  'img/grammar-quest/levels/w5-sandstorm.png':
    'img/levels/w5-sandstorm.b09c4dc0d2.webp',
  'img/grammar-quest/levels/w6-aurora-field.png':
    'img/levels/w6-aurora-field.b8f7df121d.webp',
  'img/grammar-quest/levels/w6-blizzard.png':
    'img/levels/w6-blizzard.699a8b5912.webp',
  'img/grammar-quest/levels/w6-glacier-day.png':
    'img/levels/w6-glacier-day.ec9cea8ff7.webp',
  'img/grammar-quest/levels/w6-ice-caves.png':
    'img/levels/w6-ice-caves.fa4c9a4215.webp',
  'img/grammar-quest/levels/w6-ice-palace.png':
    'img/levels/w6-ice-palace.8cdc259ba9.webp',
  'img/grammar-quest/levels/w6-penguin-floes.png':
    'img/levels/w6-penguin-floes.51f44c9856.webp',
  'img/grammar-quest/levels/w6-polar-sky.png':
    'img/levels/w6-polar-sky.813cd480ef.webp',
  'img/grammar-quest/levels/w6-snow-village.png':
    'img/levels/w6-snow-village.02015fbdbf.webp',
  'img/grammar-quest/levels/w6-under-ice.png':
    'img/levels/w6-under-ice.57a8943390.webp',
  'img/grammar-quest/levels/w7-airship-docks.png':
    'img/levels/w7-airship-docks.719faa72b1.webp',
  'img/grammar-quest/levels/w7-aurora-archive.png':
    'img/levels/w7-aurora-archive.60fdfbdb76.webp',
  'img/grammar-quest/levels/w7-balloon-armada.png':
    'img/levels/w7-balloon-armada.1024551690.webp',
  'img/grammar-quest/levels/w7-clockwork-attic.png':
    'img/levels/w7-clockwork-attic.f293bd7ba1.webp',
  'img/grammar-quest/levels/w7-cloud-kingdom.png':
    'img/levels/w7-cloud-kingdom.df8faf4fe7.webp',
  'img/grammar-quest/levels/w7-giant-books.png':
    'img/levels/w7-giant-books.f754d0fc73.webp',
  'img/grammar-quest/levels/w7-inkwell-sea.png':
    'img/levels/w7-inkwell-sea.2a7a5d8170.webp',
  'img/grammar-quest/levels/w7-map-room.png':
    'img/levels/w7-map-room.db59632275.webp',
  'img/grammar-quest/levels/w7-moon-clouds.png':
    'img/levels/w7-moon-clouds.eba1ab8ca7.webp',
  'img/grammar-quest/levels/w7-paper-planes.png':
    'img/levels/w7-paper-planes.1cd57740c8.webp',
  'img/grammar-quest/levels/w7-rainbow-bridge.png':
    'img/levels/w7-rainbow-bridge.63ccc542b2.webp',
  'img/grammar-quest/levels/w7-sky-garden.png':
    'img/levels/w7-sky-garden.57557d178d.webp',
  'img/grammar-quest/levels/w7-sky-library.png':
    'img/levels/w7-sky-library.e6c0c5c118.webp',
  'img/grammar-quest/levels/w7-starlit-reading.png':
    'img/levels/w7-starlit-reading.5ea617ea2f.webp',
  'img/grammar-quest/levels/w7-storm-clouds.png':
    'img/levels/w7-storm-clouds.d5728ecbcd.webp',
  'img/grammar-quest/levels/w7-sunset-clouds.png':
    'img/levels/w7-sunset-clouds.8ec85cfb39.webp',
  'img/grammar-quest/levels/w8-bell-tower.png':
    'img/levels/w8-bell-tower.9e56484d8f.webp',
  'img/grammar-quest/levels/w8-citadel-walls.png':
    'img/levels/w8-citadel-walls.c46a6e61ef.webp',
  'img/grammar-quest/levels/w8-dungeon.png':
    'img/levels/w8-dungeon.585d5bbffc.webp',
  'img/grammar-quest/levels/w8-ghost-house.png':
    'img/levels/w8-ghost-house.8282c946df.webp',
  'img/grammar-quest/levels/w8-lava-moat.png':
    'img/levels/w8-lava-moat.48dfb02fde.webp',
  'img/grammar-quest/levels/w9-art-room.png':
    'img/levels/w9-art-room.df6b116ece.webp',
  'img/grammar-quest/levels/w9-campus-day.png':
    'img/levels/w9-campus-day.2ff92aa5aa.webp',
  'img/grammar-quest/levels/w9-chem-lab.png':
    'img/levels/w9-chem-lab.99d6d44475.webp',
  'img/grammar-quest/levels/w9-dream-dorm.png':
    'img/levels/w9-dream-dorm.c8cc3fbb8f.webp',
  'img/grammar-quest/levels/w9-giant-classroom.png':
    'img/levels/w9-giant-classroom.7413702dbc.webp',
  'img/grammar-quest/levels/w9-greenhouse.png':
    'img/levels/w9-greenhouse.ea68c9ef29.webp',
  'img/grammar-quest/levels/w9-gym.png': 'img/levels/w9-gym.1279bd2c52.webp',
  'img/grammar-quest/levels/w9-library-night.png':
    'img/levels/w9-library-night.a22d3a4b7e.webp',
  'img/grammar-quest/levels/w9-music-hall.png':
    'img/levels/w9-music-hall.76f2e04e7e.webp',
  'img/grammar-quest/levels/w9-observatory.png':
    'img/levels/w9-observatory.01a7cbdd0c.webp',
  'img/grammar-quest/levels/w9-rooftop-night.png':
    'img/levels/w9-rooftop-night.e37f92c6b0.webp',
  'img/grammar-quest/levels/w9-sports-field.png':
    'img/levels/w9-sports-field.3a69591d9a.webp',
  'img/grammar-quest/logic-tower.jpg': 'img/logic-tower.25b83ae437.webp',
  'img/grammar-quest/passive-glacier.jpg':
    'img/passive-glacier.28774b246c.webp',
  'img/grammar-quest/sky-library.jpg': 'img/sky-library.8101e3732a.webp',
  'img/grammar-quest/starter-village.jpg':
    'img/starter-village.b847035b5f.webp',
  'img/grammar-quest/tense-canyon.jpg': 'img/tense-canyon.ff244fce51.webp',
  'img/grammar-quest/the-academy.jpg': 'img/the-academy.bbd50d902a.webp',
  'img/grammar-quest/the-citadel.jpg': 'img/the-citadel.5555d0aea7.webp',
  'img/grammar-quest/thumbs/forest-of-clauses.jpg':
    'img/thumbs/forest-of-clauses.dc8ebe1b3e.webp',
  'img/grammar-quest/thumbs/harbor-town.jpg':
    'img/thumbs/harbor-town.8144a5a937.webp',
  'img/grammar-quest/thumbs/logic-tower.jpg':
    'img/thumbs/logic-tower.946dd46e20.webp',
  'img/grammar-quest/thumbs/passive-glacier.jpg':
    'img/thumbs/passive-glacier.e7e21dc943.webp',
  'img/grammar-quest/thumbs/sky-library.jpg':
    'img/thumbs/sky-library.e3ca73a334.webp',
  'img/grammar-quest/thumbs/starter-village.jpg':
    'img/thumbs/starter-village.59a769fdd2.webp',
  'img/grammar-quest/thumbs/tense-canyon.jpg':
    'img/thumbs/tense-canyon.c4d07ebcbc.webp',
  'img/grammar-quest/thumbs/the-academy.jpg':
    'img/thumbs/the-academy.ca3f440246.webp',
  'img/grammar-quest/thumbs/the-citadel.jpg':
    'img/thumbs/the-citadel.f382fe97fd.webp',
  'img/grammar-quest/thumbs/windmill-hills.jpg':
    'img/thumbs/windmill-hills.08c3ed2baa.webp',
  'img/grammar-quest/windmill-hills.jpg': 'img/windmill-hills.83d4bfe851.webp',
  'music/grammar-quest/boss-castle.mp3': 'music/boss-castle.7cabeac702.mp3',
  'music/grammar-quest/boss-final.mp3': 'music/boss-final.c1a0341807.mp3',
  'music/grammar-quest/boss-fort.mp3': 'music/boss-fort.411f58bd86.mp3',
  'music/grammar-quest/overworld.mp3': 'music/overworld.3f8d0127b3.mp3',
  'music/grammar-quest/w1-starter-village.mp3':
    'music/w1-starter-village.1f9845b7de.mp3',
  'music/grammar-quest/w10-logic-tower.mp3':
    'music/w10-logic-tower.41c16712ae.mp3',
  'music/grammar-quest/w2-harbor-town.mp3':
    'music/w2-harbor-town.5fe1ad845a.mp3',
  'music/grammar-quest/w3-windmill-hills.mp3':
    'music/w3-windmill-hills.2118a83a9a.mp3',
  'music/grammar-quest/w4-forest-of-clauses.mp3':
    'music/w4-forest-of-clauses.50849ebdc2.mp3',
  'music/grammar-quest/w5-tense-canyon.mp3':
    'music/w5-tense-canyon.79dfb5667a.mp3',
  'music/grammar-quest/w6-passive-glacier.mp3':
    'music/w6-passive-glacier.f7da3d08c6.mp3',
  'music/grammar-quest/w7-sky-library.mp3':
    'music/w7-sky-library.a633a37c9b.mp3',
  'music/grammar-quest/w8-the-citadel.mp3':
    'music/w8-the-citadel.d47c899431.mp3',
  'music/grammar-quest/w9-the-academy.mp3':
    'music/w9-the-academy.574e591be0.mp3'
};
export const GQ_MUSIC: Record<
  string,
  {
    id: string;
    title: string;
    bpm: number;
    loopStart: number;
    loopEnd: number;
    duration: number;
  }
> = {
  'boss-castle': {
    id: 'boss-castle',
    title: 'Throne of the Grammar Warden',
    bpm: 164,
    loopStart: 5.853659,
    loopEnd: 99.512195,
    duration: 99.512195
  },
  'boss-final': {
    id: 'boss-final',
    title: 'The Sovereign of Syntax',
    bpm: 172,
    loopStart: 5.581395,
    loopEnd: 139.534884,
    duration: 139.534884
  },
  'boss-fort': {
    id: 'boss-fort',
    title: 'Siege at the Grammar Fort',
    bpm: 152,
    loopStart: 6.315789,
    loopEnd: 94.736842,
    duration: 94.736842
  },
  overworld: {
    id: 'overworld',
    title: 'Overworld',
    bpm: 120,
    loopStart: 4,
    loopEnd: 84,
    duration: 84
  },
  'w1-starter-village': {
    id: 'w1-starter-village',
    title: 'Starter Village',
    bpm: 144,
    loopStart: 3.333333,
    loopEnd: 70,
    duration: 70
  },
  'w10-logic-tower': {
    id: 'w10-logic-tower',
    title: 'Logic Tower',
    bpm: 124,
    loopStart: 7.741935,
    loopEnd: 100.645161,
    duration: 100.645161
  },
  'w2-harbor-town': {
    id: 'w2-harbor-town',
    title: 'Harbor Town',
    bpm: 330,
    loopStart: 4.363636,
    loopEnd: 82.909091,
    duration: 82.909091
  },
  'w3-windmill-hills': {
    id: 'w3-windmill-hills',
    title: 'Windmill Hills',
    bpm: 152,
    loopStart: 4.736842,
    loopEnd: 80.526316,
    duration: 80.526316
  },
  'w4-forest-of-clauses': {
    id: 'w4-forest-of-clauses',
    title: 'Forest of Clauses',
    bpm: 104,
    loopStart: 4.615385,
    loopEnd: 96.923077,
    duration: 96.923077
  },
  'w5-tense-canyon': {
    id: 'w5-tense-canyon',
    title: 'Tense Canyon',
    bpm: 124,
    loopStart: 7.741935,
    loopEnd: 100.645161,
    duration: 100.645161
  },
  'w6-passive-glacier': {
    id: 'w6-passive-glacier',
    title: 'Passive Glacier',
    bpm: 96,
    loopStart: 7.5,
    loopEnd: 97.5,
    duration: 97.5
  },
  'w7-sky-library': {
    id: 'w7-sky-library',
    title: 'Sky Library',
    bpm: 120,
    loopStart: 8,
    loopEnd: 104,
    duration: 104
  },
  'w8-the-citadel': {
    id: 'w8-the-citadel',
    title: 'The Citadel',
    bpm: 112,
    loopStart: 8.571429,
    loopEnd: 94.285714,
    duration: 94.285714
  },
  'w9-the-academy': {
    id: 'w9-the-academy',
    title: 'The Academy',
    bpm: 150,
    loopStart: 6.4,
    loopEnd: 83.2,
    duration: 83.2
  }
};
